export const START_PROBLEM_PAGE = 'START_PROBLEM_PAGE';
export const START_EXERCISES_PAGE = 'START_HOME_PAGE';
export const START_NEWS_PAGE = 'START_NEWS_PAGE';

export const REQUEST_EXERCISES_PENDING = 'REQUEST_EXERCISES_PENDING';
export const REQUEST_EXERCISES_SUCCES = 'REQUEST_EXERCISES_SUCCES';
export const REQUEST_EXERCISES_FAILED = 'REQUEST_EXERCISES_FAILED';

export const RQUEST_NEWS_PENDING = 'RQUEST_NEWS_PENDING';
export const RQUEST_NEWS_SUCCES  = 'RQUEST_NEWS_SUCCES';
export const RQUEST_NEWS_FAILED  = 'RQUEST_NEWS_FAILED';

export const RQUEST_PROBLEM_PENDING = 'RQUEST_PROBLEM_PENDING';
export const RQUEST_PROBLEM_SUCCES  = 'RQUEST_PROBLEM_SUCCES';
export const RQUEST_PROBLEM_FAILED  = 'RQUEST_PROBLEM_FAILED';
